"""initial tables

Revision ID: a5c3313f58c4
Revises: 
Create Date: 2026-06-05 23:47:58.513128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c3313f58c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=511), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_repos_github_id'), 'repos', ['github_id'], unique=True)
    op.create_index(op.f('ix_repos_name'), 'repos', ['name'], unique=False)
    op.create_index(op.f('ix_repos_owner'), 'repos', ['owner'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_token', sa.String(length=500), nullable=True),
    sa.Column('github_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plantype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='jobstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_repo_id'), 'analysis_jobs', ['repo_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('has_vulnerability', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severitytype'), nullable=True),
    sa.Column('cve_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_repo_id'), 'dependencies', ['repo_id'], unique=False)
    op.create_table('repo_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('commit_count_30d', sa.Integer(), nullable=False),
    sa.Column('commit_count_90d', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('closed_issues', sa.Integer(), nullable=False),
    sa.Column('avg_issue_response_hours', sa.Float(), nullable=False),
    sa.Column('avg_pr_merge_hours', sa.Float(), nullable=False),
    sa.Column('contributor_count', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_snapshots_repo_id'), 'repo_snapshots', ['repo_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('notify_on_score_drop', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_repo_id'), 'watchlist', ['repo_id'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_repo_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_repo_snapshots_repo_id'), table_name='repo_snapshots')
    op.drop_table('repo_snapshots')
    op.drop_index(op.f('ix_dependencies_repo_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_analysis_jobs_repo_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repos_owner'), table_name='repos')
    op.drop_index(op.f('ix_repos_name'), table_name='repos')
    op.drop_index(op.f('ix_repos_github_id'), table_name='repos')
    op.drop_table('repos')
    # ### end Alembic commands ###
